import { ArrowLeft, Building2, MapPin, Search, Star } from 'lucide-react'
import { FormEvent, useEffect, useState } from 'react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { Brand } from '../components/Brand'
import { supabase } from '../lib/supabase'

type EventInfo={name:string;slug:string;location:string}
type Result={exhibitor_id:string;public_id:string;company_name:string;asset_path:string|null;booth_ids:string[];tag_names:string[];average_rating:number|null;rating_count:number;total_count:number}
const PAGE_SIZE=24

export function EventSearchPage(){
 const {slug=''}=useParams(); const [params,setParams]=useSearchParams(); const [event,setEvent]=useState<EventInfo|null>(null); const [state,setState]=useState(''); const [results,setResults]=useState<Result[]>([]); const [loading,setLoading]=useState(true); const [input,setInput]=useState(params.get('q')??''); const page=Math.max(1,Number(params.get('page')??1)||1); const query=params.get('q')??''
 useEffect(()=>{void(async()=>{setLoading(true);const [{data:eventData},{data:stateData}]=await Promise.all([supabase.rpc('public_get_event',{p_slug:slug}),supabase.rpc('public_event_state',{p_slug:slug})]);const found=(eventData as EventInfo[]|null)?.[0]??null;setEvent(found);setState(String(stateData??'invalid'));if(found){const {data}=await supabase.rpc('public_search_exhibitors',{p_event_slug:slug,p_query:query,p_limit:PAGE_SIZE,p_offset:(page-1)*PAGE_SIZE});setResults((data??[]) as Result[])}else setResults([]);setLoading(false)})()},[slug,query,page])
 function search(e:FormEvent){e.preventDefault();const next=input.trim();setParams(next?{q:next}:{})}
 if(!loading&&!event){const messages:Record<string,string>={expired:'This event is no longer visible.',archived:'This event has been archived.',not_yet_available:'This event is not available yet.',unavailable:'This event is unavailable.',invalid:'Event not found.'};return <Unavailable message={messages[state]??messages.invalid}/>} const total=Number(results[0]?.total_count??0);const pages=Math.ceil(total/PAGE_SIZE)
 return <main className="min-h-screen bg-[#f4f7f9]"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><Brand/><Link to="/" className="btn-secondary"><ArrowLeft size={17}/>Events</Link></div></header><section className="mx-auto max-w-7xl px-5 py-10"><p className="font-bold uppercase tracking-wider text-[#ef5b32]">{event?.location}</p><h1 className="mt-2 text-4xl font-black text-[#0b2940]">{event?.name??'Loading event…'}</h1><form onSubmit={search} className="mt-8 flex max-w-3xl gap-2"><label className="relative flex-1"><Search className="absolute left-3 top-3.5 text-slate-400" size={19}/><span className="sr-only">Search exhibitors</span><input className="field mt-0 pl-10" value={input} onChange={e=>setInput(e.target.value)} placeholder="Search company, booth or tag"/></label><button className="btn-primary">Search</button></form><p className="mt-4 text-sm text-slate-500">{loading?'Searching…':`${total} exhibitor${total===1?'':'s'} found`}</p><div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{results.map(item=><Link className="card p-5 transition hover:shadow-md" key={item.exhibitor_id} to={`/e/${slug}/exhibitors/${item.public_id}`}><div className="flex gap-4"><Logo item={item}/><div className="min-w-0"><h2 className="text-lg font-black text-slate-900">{item.company_name}</h2><p className="mt-2 flex gap-2 text-sm text-slate-600"><MapPin size={16}/>{item.booth_ids.length?item.booth_ids.join(', '):'Booth not allocated'}</p>{Number(item.rating_count)>0&&<p className="mt-2 flex gap-1 text-sm"><Star size={16} className="fill-amber-400 text-amber-400"/>{Number(item.average_rating).toFixed(1)} ({item.rating_count})</p>}</div></div><div className="mt-4 flex flex-wrap gap-2">{item.tag_names.map(tag=><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold" key={tag}>{tag}</span>)}</div></Link>)}</div>{!loading&&total===0&&<div className="card mt-6 p-8 text-center"><Building2 className="mx-auto text-slate-400"/><h2 className="mt-3 font-bold">No exhibitors found</h2><p className="text-slate-500">Try another company, booth or tag.</p></div>}<div className="mt-8 flex justify-center gap-3">{page>1&&<button className="btn-secondary" onClick={()=>setParams(query?{q:query,page:String(page-1)}:{page:String(page-1)})}>Previous</button>}{page<pages&&<button className="btn-secondary" onClick={()=>setParams(query?{q:query,page:String(page+1)}:{page:String(page+1)})}>Next</button>}</div></section></main>
}
function Logo({item}:{item:Result}){const initials=item.company_name.replace(/[^a-z0-9]/gi,'').slice(0,2).toUpperCase();return item.asset_path?<img className="size-14 rounded-xl object-contain" src={item.asset_path} alt=""/>:<span className="grid size-14 shrink-0 place-items-center rounded-xl bg-[#0b2940] font-black text-white">{initials||'EX'}</span>}
function Unavailable({message}:{message:string}){return <main className="grid min-h-screen place-items-center bg-[#f4f7f9] p-5"><div className="card max-w-lg p-8 text-center"><Building2 className="mx-auto text-[#ef5b32]"/><h1 className="mt-4 text-2xl font-black">Exhibitors unavailable</h1><p className="mt-2 text-slate-600">{message}</p><Link className="btn-primary mt-6" to="/">Return to home</Link></div></main>}
