import { ArrowLeft, Save } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { supabase } from '../lib/supabase'
type Tag={tag_id:string;name:string;status:'active'|'archived'}
export function ExhibitorFormPage(){const {eventId,exhibitorId}=useParams();const navigate=useNavigate();const editing=Boolean(exhibitorId);const [name,setName]=useState('');const [website,setWebsite]=useState('');const [description,setDescription]=useState('');const [assetPath,setAssetPath]=useState('');const [booths,setBooths]=useState('');const [tagIds,setTagIds]=useState<string[]>([]);const [tags,setTags]=useState<Tag[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('')
  useEffect(()=>{if(eventId)void supabase.rpc('manage_list_tags',{p_event_id:eventId}).then(({data})=>setTags((data??[]) as Tag[]));if(exhibitorId)void supabase.rpc('manage_get_exhibitor',{p_exhibitor_id:exhibitorId}).then(({data,error})=>{if(error)setError(error.message);else if(data){setName(data.company_name);setWebsite(data.website_url??'');setDescription(data.description??'');setAssetPath(data.asset_path??'');setBooths((data.booth_ids??[]).join(', '));setTagIds(data.tag_ids??[])}})},[eventId,exhibitorId])
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');const boothIds=booths.split(',').map(x=>x.trim().toUpperCase()).filter(Boolean);const invalid=boothIds.find(x=>!/^[A-Z0-9#.-]{2,12}$/.test(x));if(invalid){setError(`Invalid Booth ID: ${invalid}`);setBusy(false);return}const {error}=await supabase.rpc('manage_save_exhibitor',{p_event_id:eventId,p_exhibitor_id:exhibitorId??null,p_company_name:name,p_website_url:website,p_description:description,p_asset_path:assetPath,p_booth_ids:boothIds,p_tag_ids:tagIds});if(error)setError(error.message);else navigate(`/manage/events/${eventId}/exhibitors`);setBusy(false)}
  return <><Link to={`/manage/events/${eventId}/exhibitors`} className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowLeft size={17}/>Exhibitors</Link><div className="mt-5"><p className="text-sm font-bold uppercase tracking-[.16em] text-[#ef5b32]">Directory record</p><h1 className="mt-2 text-3xl font-black text-[#0b2940]">{editing?'Edit Exhibitor':'Add Exhibitor'}</h1></div><form onSubmit={submit} className="card mt-7 max-w-3xl p-6"><div className="grid gap-5 sm:grid-cols-2"><label className="block sm:col-span-2"><span className="label">Company Name</span><input className="field" required value={name} onChange={e=>setName(e.target.value)}/></label><label className="block"><span className="label">Website <span className="font-normal text-slate-400">(optional)</span></span><input className="field" type="url" placeholder="https://example.com" value={website} onChange={e=>setWebsite(e.target.value)}/></label><label className="block"><span className="label">Asset path <span className="font-normal text-slate-400">(optional)</span></span><input className="field" placeholder="/assets/exhibitors/logo.webp" value={assetPath} onChange={e=>setAssetPath(e.target.value)}/></label><label className="block sm:col-span-2"><span className="label">Description</span><textarea className="field min-h-28" value={description} onChange={e=>setDescription(e.target.value)}/></label><label className="block sm:col-span-2"><span className="label">Booth IDs</span><input className="field" placeholder="A101, A102 (leave empty for Booth TBA)" value={booths} onChange={e=>setBooths(e.target.value)}/><span className="mt-1.5 block text-xs text-slate-500">Comma-separated; A–Z, 0–9, #, period and hyphen, 2–12 characters.</span></label><fieldset className="sm:col-span-2"><legend className="label">Tags</legend><div className="mt-2 flex flex-wrap gap-2">{tags.filter(t=>t.status==='active').map(tag=><label key={tag.tag_id} className={`cursor-pointer rounded-full border px-3 py-2 text-sm font-semibold ${tagIds.includes(tag.tag_id)?'border-orange-300 bg-orange-50 text-[#d94722]':'border-slate-200 text-slate-600'}`}><input className="sr-only" type="checkbox" checked={tagIds.includes(tag.tag_id)} onChange={()=>setTagIds(current=>current.includes(tag.tag_id)?current.filter(id=>id!==tag.tag_id):[...current,tag.tag_id])}/>{tag.name}</label>)}{!tags.some(t=>t.status==='active')&&<p className="text-sm text-slate-500">No active Tags. Create them from the Tag catalogue.</p>}</div></fieldset></div>{error&&<p className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button className="btn-primary mt-6" disabled={busy}><Save size={18}/>{busy?'Saving…':'Save Exhibitor'}</button></form></>}

