import { ArrowLeft, Building2, FileUp, Plus, Search, Tags } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { companyInitials } from '../lib/text'
import { useAuth } from '../providers/AuthProvider'

type ExhibitorRow={exhibitor_id:string;company_name:string;website_url:string|null;status:'active'|'archived';booth_ids:string[];tag_names:string[]}
export function ExhibitorsPage(){const {eventId}=useParams();const {profile}=useAuth();const [rows,setRows]=useState<ExhibitorRow[]>([]);const [query,setQuery]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState('')
  useEffect(()=>{if(eventId)void supabase.rpc('manage_list_exhibitors',{p_event_id:eventId}).then(({data,error})=>{if(error)setError(error.message);else setRows(data??[]);setLoading(false)})},[eventId])
  const filtered=useMemo(()=>rows.filter(row=>[row.company_name,...row.booth_ids,...row.tag_names].join(' ').toLowerCase().includes(query.toLowerCase())),[rows,query])
  return <><Link to={`/manage/events/${eventId}`} className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-slate-900"><ArrowLeft size={17}/>Event overview</Link><div className="mt-5 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-[#ef5b32]">Event directory</p><h1 className="mt-2 text-3xl font-black tracking-tight text-[#0b2940]">Exhibitors</h1><p className="mt-2 text-slate-600">Manage companies, Booth assignments and discovery Tags.</p></div><div className="flex flex-wrap gap-2"><Link to={`/manage/events/${eventId}/tags`} className="btn-secondary"><Tags size={18}/>Tags</Link>{profile?.role==='admin'&&<><Link to={`/manage/events/${eventId}/import`} className="btn-secondary"><FileUp size={18}/>Import JSON</Link><Link to={`/manage/events/${eventId}/exhibitors/new`} className="btn-primary"><Plus size={18}/>Add Exhibitor</Link></>}</div></div>
  <section className="card mt-7 overflow-hidden"><div className="border-b border-slate-200 p-5"><label className="relative block max-w-md"><Search className="absolute left-3 top-3 text-slate-400" size={19}/><input className="field mt-0 pl-10" placeholder="Search company, Booth or Tag" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>{error?<p className="p-5 text-red-700">{error}</p>:loading?<p className="p-10 text-center text-slate-500">Loading Exhibitors…</p>:filtered.length===0?<div className="p-12 text-center"><Building2 className="mx-auto text-slate-300" size={38}/><h2 className="mt-4 text-xl font-bold text-slate-800">No Exhibitors found</h2><p className="mt-2 text-slate-500">Create one manually or import your JSON file.</p></div>:<div className="divide-y divide-slate-100">{filtered.map(row=><Link to={`/manage/events/${eventId}/exhibitors/${row.exhibitor_id}`} key={row.exhibitor_id} className="flex items-center gap-4 p-5 hover:bg-slate-50"><div className="grid size-11 shrink-0 place-items-center rounded-xl bg-orange-50 font-black text-[#d94722]">{companyInitials(row.company_name)}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="truncate font-bold text-slate-900">{row.company_name}</p>{row.status==='archived'&&<span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold uppercase text-slate-500">Archived</span>}</div><p className="mt-1 text-sm text-slate-500">{row.booth_ids.length?`Booths: ${row.booth_ids.join(', ')}`:'Booth TBA'}{row.tag_names.length?` · ${row.tag_names.join(', ')}`:''}</p></div></Link>)}</div>}</section></>}
