import { ArrowLeft, Building2, FileUp, Plus, Search, Tags } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { companyInitials } from '../lib/text'
import { useAuth } from '../providers/AuthProvider'

type ExhibitorRow={exhibitor_id:string;company_name:string;status:'active'|'archived';booth_ids:string[];tag_names:string[]}
type Tag={tag_id:string;name:string;status:'active'|'archived'}
export function ExhibitorsPage(){const {eventId}=useParams();const {profile}=useAuth();const [rows,setRows]=useState<ExhibitorRow[]>([]);const [tags,setTags]=useState<Tag[]>([]);const [initialsMap,setInitialsMap]=useState<Record<string,string>>({});const [query,setQuery]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState('');const [error,setError]=useState('')
  useEffect(()=>{if(!eventId)return;void Promise.all([supabase.rpc('manage_list_exhibitors',{p_event_id:eventId}),supabase.rpc('manage_list_tags',{p_event_id:eventId}),supabase.rpc('manage_get_exhibitor_initials_map',{p_event_id:eventId})]).then(([exhibitorsResult,tagsResult,initialsResult])=>{if(exhibitorsResult.error)setError(exhibitorsResult.error.message);else setRows((exhibitorsResult.data??[]) as ExhibitorRow[]);if(tagsResult.error)setError(tagsResult.error.message);else setTags((tagsResult.data??[]) as Tag[]);if(initialsResult.error)setError(initialsResult.error.message);else setInitialsMap((initialsResult.data??{}) as Record<string,string>);setLoading(false)})},[eventId])
  const activeTags=tags.filter(tag=>tag.status==='active');const filtered=useMemo(()=>rows.filter(row=>[row.company_name,...row.booth_ids,...row.tag_names].join(' ').toLowerCase().includes(query.toLowerCase())),[rows,query])
  async function toggleTag(row:ExhibitorRow,tag:Tag){const next=row.tag_names.includes(tag.name)?row.tag_names.filter(name=>name!==tag.name):[...row.tag_names,tag.name];const tagIds=activeTags.filter(item=>next.includes(item.name)).map(item=>item.tag_id);setSaving(row.exhibitor_id);setError('');const {error}=await supabase.rpc('manage_set_exhibitor_tags',{p_exhibitor_id:row.exhibitor_id,p_tag_ids:tagIds});if(error)setError(error.message);else setRows(current=>current.map(item=>item.exhibitor_id===row.exhibitor_id?{...item,tag_names:next.sort((a,b)=>a.localeCompare(b))}:item));setSaving('')}
  return <><Link to={`/manage/events/${eventId}`} className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-slate-900"><ArrowLeft size={17}/>Event overview</Link><div className="mt-5 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-[#ef5b32]">Event directory</p><h1 className="mt-2 text-3xl font-black tracking-tight text-[#0b2940]">Exhibitors</h1><p className="mt-2 text-slate-600">Manage companies, Booth assignments and discovery Tags.</p></div><div className="flex flex-wrap gap-2"><Link to={`/manage/events/${eventId}/tags`} className="btn-secondary"><Tags size={18}/>Tags</Link>{profile?.role==='admin'&&<><Link to={`/manage/events/${eventId}/import`} className="btn-secondary"><FileUp size={18}/>Import JSON</Link><Link to={`/manage/events/${eventId}/exhibitors/new`} className="btn-primary"><Plus size={18}/>Add Exhibitor</Link></>}</div></div>
  <section className="card mt-7 overflow-visible"><div className="border-b border-slate-200 p-5"><label className="relative block max-w-md"><Search className="absolute left-3 top-3 text-slate-400" size={19}/><span className="sr-only">Search Exhibitors</span><input className="field mt-0 pl-10" placeholder="Search company, Booth or Tag" value={query} onChange={e=>setQuery(e.target.value)}/></label>{error&&<p className="mt-3 text-sm text-red-700">{error}</p>}</div>{loading?<p className="p-10 text-center text-slate-500">Loading Exhibitors…</p>:filtered.length===0?<div className="p-12 text-center"><Building2 className="mx-auto text-slate-300" size={38}/><h2 className="mt-4 text-xl font-bold text-slate-800">No Exhibitors found</h2></div>:<div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-3">Initials</th><th className="px-5 py-3">Name</th><th className="px-5 py-3">Booth IDs</th><th className="px-5 py-3">Tags</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map(row=><tr key={row.exhibitor_id} className="align-top hover:bg-slate-50"><td className="px-5 py-4"><span className="grid size-10 place-items-center rounded-xl bg-orange-50 font-black text-[#d94722]">{initialsMap[row.exhibitor_id]??companyInitials(row.company_name)}</span></td><td className="px-5 py-4"><Link className="font-bold text-slate-900 hover:text-[#d94722]" to={`/manage/events/${eventId}/exhibitors/${row.exhibitor_id}`}>{row.company_name}</Link>{row.status==='archived'&&<span className="ml-2 rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold uppercase text-slate-500">Archived</span>}</td><td className="px-5 py-4 text-sm text-slate-600">{row.booth_ids.length?row.booth_ids.join(', '):'Booth TBA'}</td><td className="px-5 py-4"><details className="relative"><summary className="inline-flex cursor-pointer list-none flex-wrap items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm hover:bg-slate-50">{row.tag_names.length?row.tag_names.map(name=><span key={name} className="rounded-full bg-orange-50 px-2 py-0.5 text-xs font-semibold text-[#c94722]">{name}</span>):<span className="text-slate-500">Add Tags</span>}</summary><div className="absolute right-0 z-20 mt-2 w-64 rounded-xl border border-slate-200 bg-white p-3 shadow-xl">{activeTags.map(tag=><label key={tag.tag_id} className="flex cursor-pointer items-center gap-2 rounded-lg px-2 py-2 text-sm hover:bg-slate-50"><input type="checkbox" checked={row.tag_names.includes(tag.name)} disabled={saving===row.exhibitor_id} onChange={()=>void toggleTag(row,tag)}/><span>{tag.name}</span></label>)}{activeTags.length===0&&<p className="text-sm text-slate-500">No active Tags.</p>}{saving===row.exhibitor_id&&<p className="mt-2 text-xs text-slate-500">Saving…</p>}</div></details></td></tr>)}</tbody></table></div>}</section></>}
