create or replace function public.admin_update_exhibitor_booths(p_event_id uuid,p_records jsonb,p_dry_run boolean default true)
returns jsonb language plpgsql security definer set search_path='' as $$
declare actor uuid;errors jsonb:='[]';changes jsonb:='[]';row_item jsonb;row_index integer:=0;company text;company_key text;exhibitor_ref uuid;old_booths text[];new_booths text[];booth_value jsonb;booth text;seen_companies text[]:='{}';seen_booths text[]:='{}';targets uuid[]:='{}';change_item jsonb;conflict_company text;
begin
 if not public.is_admin() then raise exception 'Only Admin can update Booth IDs';end if;actor:=public.current_profile_id();
 if not exists(select 1 from public.events where event_id=p_event_id) then raise exception 'Event not found';end if;
 if jsonb_typeof(p_records)<>'array' or jsonb_array_length(p_records)=0 then return jsonb_build_object('valid',false,'errors',jsonb_build_array('The file must contain a non-empty JSON array.'),'changes','[]'::jsonb);end if;
 for row_item in select value from jsonb_array_elements(p_records) loop row_index:=row_index+1;company:=btrim(coalesce(row_item->>'companyName',''));company_key:=lower(company);new_booths:='{}';exhibitor_ref:=null;
   if jsonb_typeof(row_item)<>'object' then errors:=errors||jsonb_build_array(format('Entry %s: must be an object.',row_index));continue;end if;
   if company='' then errors:=errors||jsonb_build_array(format('Entry %s: companyName is required.',row_index));
   elsif company_key=any(seen_companies) then errors:=errors||jsonb_build_array(format('Entry %s: duplicate companyName: %s',row_index,company));
   else seen_companies:=array_append(seen_companies,company_key);select x.exhibitor_id into exhibitor_ref from public.exhibitors x where x.event_id=p_event_id and lower(btrim(x.company_name))=company_key;if exhibitor_ref is null then errors:=errors||jsonb_build_array(format('Entry %s: Unknown companyName: %s',row_index,company));else targets:=array_append(targets,exhibitor_ref);end if;end if;
   if not(row_item?'boothIds') then errors:=errors||jsonb_build_array(format('Entry %s: boothIds is required.',row_index));
   elsif jsonb_typeof(row_item->'boothIds')<>'array' then errors:=errors||jsonb_build_array(format('Entry %s: boothIds must be an array.',row_index));
   else for booth_value in select value from jsonb_array_elements(row_item->'boothIds') loop if jsonb_typeof(booth_value)<>'string' then errors:=errors||jsonb_build_array(format('Entry %s: every Booth ID must be a string.',row_index));continue;end if;booth:=upper(btrim(booth_value#>>'{}'));if booth!~'^[A-Z0-9#.-]{2,12}$' then errors:=errors||jsonb_build_array(format('Entry %s: invalid Booth ID: %s',row_index,booth));elsif booth=any(new_booths) then errors:=errors||jsonb_build_array(format('Entry %s: duplicate Booth ID: %s',row_index,booth));elsif booth=any(seen_booths) then errors:=errors||jsonb_build_array(format('Entry %s: Booth ID is assigned more than once in the file: %s',row_index,booth));else new_booths:=array_append(new_booths,booth);seen_booths:=array_append(seen_booths,booth);end if;end loop;end if;
   if exhibitor_ref is not null then select coalesce(array_agg(b.booth_id order by b.booth_id),'{}') into old_booths from public.exhibitor_booths b where b.exhibitor_id=exhibitor_ref;changes:=changes||jsonb_build_array(jsonb_build_object('entry',row_index,'exhibitorId',exhibitor_ref,'companyName',company,'oldBoothIds',old_booths,'newBoothIds',new_booths));end if;
 end loop;
 foreach booth in array seen_booths loop select x.company_name into conflict_company from public.exhibitor_booths b join public.exhibitors x on x.exhibitor_id=b.exhibitor_id where b.event_id=p_event_id and b.booth_id=booth and not(b.exhibitor_id=any(targets)) limit 1;if conflict_company is not null then errors:=errors||jsonb_build_array(format('Booth ID %s is already assigned to unlisted company: %s',booth,conflict_company));conflict_company:=null;end if;end loop;
 if jsonb_array_length(errors)>0 then return jsonb_build_object('valid',false,'errors',errors,'changes',changes,'updated',0);end if;
 if p_dry_run then return jsonb_build_object('valid',true,'errors',errors,'changes',changes,'updated',0);end if;
 delete from public.exhibitor_booths where exhibitor_id=any(targets);
 for change_item in select value from jsonb_array_elements(changes) loop exhibitor_ref:=(change_item->>'exhibitorId')::uuid;for booth_value in select value from jsonb_array_elements(change_item->'newBoothIds') loop booth:=booth_value#>>'{}';insert into public.exhibitor_booths(event_id,exhibitor_id,booth_id,created_by_profile_id) values(p_event_id,exhibitor_ref,booth,actor);end loop;update public.exhibitors set updated_by_profile_id=actor,updated_at=now() where exhibitor_id=exhibitor_ref;insert into public.audit_log(actor_profile_id,action,entity_type,entity_id,event_id,change_information) values(actor,'exhibitor.booths_replaced','exhibitor',exhibitor_ref,p_event_id,jsonb_build_object('oldBoothIds',change_item->'oldBoothIds','newBoothIds',change_item->'newBoothIds'));end loop;
 insert into public.audit_log(actor_profile_id,action,entity_type,entity_id,event_id,change_information) values(actor,'event.booth_update_imported','event',p_event_id,p_event_id,jsonb_build_object('updated',jsonb_array_length(changes)));
 return jsonb_build_object('valid',true,'errors',errors,'changes',changes,'updated',jsonb_array_length(changes));
end $$;
grant execute on function public.admin_update_exhibitor_booths(uuid,jsonb,boolean) to authenticated;
